### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length <>; 2 is required

### ISSUE THREAD

**Issue by IlyaMescheryakov1402** [allegroai/clearml-serving#61]
Hi everyone! I use command to create entrypoint:

```
clearml-serving --id "<>" model add --engine triton --endpoint 'conformer_joint' --model-id '<>' --preprocess 'preprocess_joint.py' --input-size '[1, 640]' '[640, 1]' --input-name 'encoder_outputs' 'decoder_outputs' --input-type float32 float32 --output-size '[100]' --output-name 'outputs' --output-type float32 --aux-config name=\"conformer_joint\" max_batch_size=16 dynamic_batching.max_queue_delay_microseconds=100 platform=\"onnxruntime_onnx\" default_model_filename=\"model.bin\"
```

this command creates `config.pbtxt` like that (copied from logs):

```
name: "conformer_joint"
platform: "onnxruntime_onnx"
default_model_filename: "model.bin"
input: [{
    dims: [-1, 1, 640]
    data_type: TYPE_FP32
    name: "encoder_outputs"
  },
  {
    dims: [-1, 640, 1]
    data_type: TYPE_FP32
    name: "decoder_outputs"
  }]
output: [{
    dims: [-1, 129]
    data_type: TYPE_FP32
    name: "outputs"
  }]
  ```
  
Logs from k8s:
```
I0802 22:48:17.274440 53 model_repository_manager.cc:1206] loading: conformer_joint:1
I0802 22:48:17.274536 53 onnxruntime.cc:2560] TRITONBACKEND_ModelInitialize: conformer_joint (version 1)
I0802 22:48:17.274881 53 onnxruntime.cc:666] skipping model configuration auto-complete for 'conformer_joint': inputs and outputs already specified
I0802 22:48:17.276238 53 onnxruntime.cc:2603] TRITONBACKEND_ModelInstanceInitialize: conformer_joint (GPU device 0)
I0802 22:48:17.279143 53 model_repository_manager.cc:1352] successfully loaded 'conformer_joint' version 1
 ```

And there are no error in clearml-serving. But when I'm trying to create request like that

```
import numpy as np
import requests
r = requests.post(f"<URL>", json={"encoder_outputs": np.random.randn(1, 1, 640).tolist(), "decoder_outputs": np.random.randn(1, 640, 1).tolist()})
r.json()
```

I get this:

```
[2023-08-02 23:02:51 +0000] [113] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fastapi/encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
           ^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 129; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/root/clearml/clearml_serving/serving/main.py", line 31, in custom_route_handler
    return await original_route_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 255, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 152, in serialize_response
    return jsonable_encoder(response_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
                    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [ValueError('dictionary update sequence element #0 has length 129; 2 is required'), TypeError('vars() argument must have __dict__ attribute')]
```

I think this is because of batch size and maybe I need to add something in `config.pbtxt`. Any ideas?

Thanks in advance!

**Comment by IlyaMescheryakov1402** [comment]
Nevermind, in `postprocess` function one need to remember use 
```
return {"data":data.tolist()}
```
Instead of 
```
return {"data":data}
```

**Comment by jkhenning** [comment]
@IlyaMescheryakov1402 closing this, please reopen if required 🙂
